### ISSUE TITLE
Search points to quarkus.io even when testing locally

### ISSUE THREAD

**Issue by gsmet** [quarkusio/search.quarkus.io#273]
When I run the quarkus.io website locally and want to have access to a guide, I search for it, click, and I end up on quarkus.io, which is unfortunate.

Ideally, when run locally, the quarkus.io links should point to local (i.e. `http://localhost:4000/` in my case).

Not sure how easy it would be but it's a bit annoying (especially if you don't notice it right away :)).

**Comment by yrodiere** [comment]
(BTW, same problem for localized websites, though I suspect it's unlikely one would run all those websites at the same time)

**Comment by marko-bekhta** [comment]
Maybe we can return relative links for the quarkus guides and absolute ones for the Quarkiverse?

**Comment by yrodiere** [comment]
Oh, you're most likely hitting staging then.

> Maybe we can return relative links for the quarkus guides and absolute ones for the Quarkiverse?

The problem is... relative to what? What about localized websites?

Also, does this kind of thing really have a place in a backend?

Maybe instead we could relativize links when rendering them in the web component? I.e. whoever uses the web component can optionally pass a "canonical URL" argument (set to the URL we expect to be used in prod), and the web component strips it?

Then we could make sure that quarkus.io sets the argument correctly so that even when running locally, the links to prod get relativized and point directly to the local instance of quarkus.io.

**Comment by marko-bekhta** [comment]
Thinking more about it ... if a quakrus.io is running locally without the search.quarkus.io then it'll be searching against the content of the "remote" quarkus.io... so maybe the solution here would be - if you are running it locally then it should fallback to javascript-local search instead ?

**Comment by yrodiere** [comment]
> Thinking more about it ... if a quakrus.io is running locally without the search.quarkus.io then it'll be searching against the content of the "remote" quarkus.io... so maybe the solution here would be - if you are running it locally then it should fallback to javascript-local search instead ?

Nah, it uses staging in that case.

But, see my answer just above.

**Comment by marko-bekhta** [comment]
> The problem is... relative to what? What about localized websites? 

Well, I was thinking... 😃  relative to the site you are searching from, localized sites should set the corresponding language in the component attribute that is passed to as a "filter". and the diff between the localized sites is in the domain name not the path, right? 

> Nah, it uses staging in that case.

Well, it's still "remote," 😃 meaning it's going to search against content that is possibly different from the content of the local site you are running, no?

**Comment by marko-bekhta** [comment]
> Also, does this kind of thing really have a place in a backend?
>
> Maybe instead we could relativize links when rendering them in the web component? I.e. whoever uses the web component can optionally pass a "canonical URL" argument (set to the URL we expect to be used in prod), and the web component strips it from matching guide links?

that might work as well 😃, I guess it's the usual "Who should do the work UI or backend?" question 😄

**Comment by yrodiere** [comment]
Presentation and contextualization is UI work, change my mind :)

**Comment by gsmet** [comment]
To clarify, I was thinking that the frontend could tell the backend `hey the url for quarkus.io is localhost:4000` or if you are testing the es website `hey, the url for es.quarkus.io is localhost:4000`.

Now I haven't followed the latest developments so not sure how easy it would be.

We could also use the Javascript search by default when testing locally. It's good enough to find a guide quickly and make sure it's ok.

**Comment by yrodiere** [comment]
> To clarify, I was thinking that the frontend could tell the backend `hey the url for quarkus.io is localhost:4000` or if you are testing the es website `hey, the url for es.quarkus.io is localhost:4000`.

More or less the same idea here, except I'd do it in the javascript instead.

URLs in the backend are actually indexed as absolute, so either way we'll just end up making (some) URLs relative. Might as well do it directly in the webcomponent when rendering, rather than delegating it all to the backend.

> We could also use the Javascript search by default when testing locally. It's good enough to find a guide quickly and make sure it's ok.

But then it'll be a problem for people testing search integration on quarkus.io.

Yeah no, let's just relativize matching URLs in the webcomponent. I can't do it right now, but next week possibly. Or earlier if someone else can do it.

**Comment by gsmet** [comment]
> But then it'll be a problem for people testing search integration on quarkus.io.

Well, not really, we could have a specific config file for that, with a specific script that sets up everything properly.

But your call really.

**Comment by marko-bekhta** [comment]
> if someone else can do it.

If we agree that we do it on the UI side 😏 I can take a look, to switch from figuring out why ORM is doing what it's doing 😄

**Comment by yrodiere** [comment]
> If we agree that we do it on the UI side 😏 I can take a look

Great, thanks!

> figuring out why ORM is doing what it's doing 😄

Don't we all.
